name: dartssh
version: 1.0.4+4
publish_to: none
description: Dart SSH package providing First-class tunnelling primitives.
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/dartssh

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  asn1lib: ^0.5.15  
  convert: ^3.0.0
  http: ^0.12.2  
  meta: ^1.2.4  
  pedantic: ^1.9.2  
  pointycastle: ^1.0.2  
  validators: ^2.0.0+1
  tweetnacl:
    path: tweetnacl-dart

dev_dependencies:
  build_runner: ^1.4.0
  test: ^1.6.5

#PS C:\Users\chelm\Desktop\dev\dartssh> pub outdated
#Resolving...
#Dependencies                Current    Upgradable  Resolvable  Latest   
#asn1lib                     *0.5.15    *0.5.15     *0.8.1      1.0.0    
#convert                     *2.1.1     *2.1.1      *2.1.1      3.0.0    
#http                        *0.12.2    *0.12.2     *0.12.2     0.13.3   
#meta                        *1.2.4     *1.2.4      *1.2.4      1.3.0    
#pedantic                    *1.9.2     *1.9.2      *1.9.2      1.11.0   
#pointycastle                *1.0.2     *1.0.2      *2.0.1      3.0.1    
#validators                  *2.0.0+1   *2.0.0+1    *2.0.1      3.0.0    
#
#dev_dependencies
#build_runner                *1.11.1    *1.11.1     *1.11.1     2.0.3    
#test                        *1.15.7    *1.15.7     *1.15.7     1.17.4   
#
#transitive dependencies
#basic_utils                 -          -           *2.7.1      3.0.2    
#charcode                    *1.1.3     *1.1.3      *1.1.3      1.2.0    
#collection                  *1.14.13   *1.14.13    *1.14.13    1.15.0   
#crypto                      *2.1.5     *2.1.5      *2.1.5      3.0.1    
#fixnum                      *0.10.11   *0.10.11    *0.10.11    1.0.0     
#http_parser                 *3.1.4     *3.1.4      *3.1.4      4.0.0    
#json_annotation             *3.1.1     *3.1.1      *3.1.1      4.0.1    
#logging                     *0.11.4    *0.11.4     *0.11.4     1.0.1
#path                        *1.7.0     *1.7.0      *1.7.0      1.8.0
#random_string               -          -           2.1.0       2.1.0
#source_span                 *1.7.0     *1.7.0      *1.7.0      1.8.1
#string_scanner              *1.0.5     *1.0.5      *1.0.5      1.1.0    
#term_glyph                  *1.1.0     *1.1.0      *1.1.0      1.2.0
#typed_data                  *1.2.0     *1.2.0      *1.2.0      1.3.0
#vin_decoder                 -          -           0.1.3       0.1.3
#
#transitive dev_dependencies
#_fe_analyzer_shared         *14.0.0    *14.0.0     *14.0.0     21.0.0
#analyzer                    *0.41.2    *0.41.2     *0.41.2     1.5.0
#args                        *1.6.0     *1.6.0      *1.6.0      2.1.0
#async                       *2.4.2     *2.4.2      *2.4.2      2.6.1
#boolean_selector            *2.0.0     *2.0.0      *2.0.0      2.1.0
#build                       *1.6.2     *1.6.2      *1.6.2      2.0.1    
#build_config                *0.4.5     *0.4.5      *0.4.5      1.0.0
#build_daemon                *2.1.7     *2.1.7      *2.1.7      3.0.0
#build_resolvers             *1.5.3     *1.5.3      *1.5.3      2.0.1
#build_runner_core           *6.1.7     *6.1.7      *6.1.7      7.0.0
#built_collection            *4.3.2     *4.3.2      *4.3.2      5.0.0
#built_value                 *7.1.0     *7.1.0      *7.1.0      8.0.6
#checked_yaml                *1.0.4     *1.0.4      *1.0.4      2.0.1    
#cli_util                    *0.2.0     *0.2.0      *0.2.0      0.3.0
#code_builder                *3.7.0     *3.7.0      *3.7.0      4.0.0
#coverage                    *0.14.2    *0.14.2     *0.14.2     1.0.2
#dart_style                  *1.3.12    *1.3.12     *1.3.12     2.0.1
#file                        *5.2.1     *5.2.1      *5.2.1      6.1.0
#glob                        *1.2.0     *1.2.0      *1.2.0      2.0.1
#graphs                      *0.2.0     *0.2.0      *0.2.0      2.0.0    
#http_multi_server           *2.2.0     *2.2.0      *2.2.0      3.0.1
#intl                        *0.16.1    *0.16.1     *0.16.1     0.17.0
#io                          *0.3.5     *0.3.5      *0.3.5      1.0.0
#js                          *0.6.2     *0.6.2      *0.6.2      0.6.3
#matcher                     *0.12.9    *0.12.9     *0.12.9     0.12.10
#mime                        *0.9.7     *0.9.7      *0.9.7      1.0.0    
#node_interop                *1.2.1     *1.2.1      *1.2.1      2.0.1
#node_io                     *1.2.0     *1.2.0      *1.2.0      2.0.0
#node_preamble               *1.4.13    *1.4.13     *1.4.13     2.0.0
#package_config              *1.9.3     *1.9.3      *1.9.3      2.0.0
#pool                        *1.4.0     *1.4.0      *1.4.0      1.5.0
#pub_semver                  *1.4.4     *1.4.4      *1.4.4      2.0.0
#pubspec_parse               *0.1.8     *0.1.8      *0.1.8      1.0.0
#quiver                      *2.1.5     *2.1.5      *2.1.5      3.0.1
#shelf                       *0.7.9     *0.7.9      *0.7.9      1.1.4
#shelf_packages_handler      *2.0.1     *2.0.1      *2.0.1      3.0.0
#shelf_static                *0.2.9+2   *0.2.9+2    *0.2.9+2    1.0.0    
#shelf_web_socket            *0.2.4+1   *0.2.4+1    *0.2.4+1    1.0.1
#source_map_stack_trace      *2.0.0     *2.0.0      *2.0.0      2.1.0
#source_maps                 *0.10.9    *0.10.9     *0.10.9     0.10.10
#stack_trace                 *1.9.6     *1.9.6      *1.9.6      1.10.0
#stream_channel              *2.0.0     *2.0.0      *2.0.0      2.1.0
#stream_transform            *1.2.0     *1.2.0      *1.2.0      2.0.0
#test_api                    *0.2.18+1  *0.2.18+1   *0.2.18+1   0.4.0
#test_core                   *0.3.11+4  *0.3.11+4   *0.3.11+4   0.3.24
#timing                      *0.1.1+3   *0.1.1+3    *0.1.1+3    1.0.0
#vm_service                  *4.2.0     *4.2.0      *4.2.0      7.0.0
#watcher                     *0.9.7+15  *0.9.7+15   *0.9.7+15   1.0.0
#web_socket_channel          *1.2.0     *1.2.0      *1.2.0      2.1.0
#webkit_inspection_protocol  *0.7.5     *0.7.5      *0.7.5      1.0.0
#yaml                        *2.2.1     *2.2.1      *2.2.1      3.1.0
#
#3  dependencies are constrained to versions that are older than a resolvable version.
#To update these dependencies, edit pubspec.yaml.
#PS C:\Users\chelm\Desktop\dev\dartssh>
#